### ISSUE TITLE
Crate serialization issues

### ISSUE THREAD

**Issue by puigru** [Hazebyte/CrateReloadedAPI#23] opened 2018-03-06 21:56 UTC
* ~~Missing messages~~
* ~~Missing effects~~
* ~~Keys 'preview.enabled' and 'preview.rows' are hierachically incorrect~~
* ~~Section symbols are not converted back to ampersands~~
* ~~Items with no name are incorrectly assigned the name of the Material type~~
* ~~Reward lines end with with an extra comma and space~~
* ~~'glow:true' is converted to 'arrow_infinite:10' and 'hide:true'~~

New bugs (as of 10/03):
* Effects are hierachically incorrect
* Display name section symbols not converted back to ampersands

**Comment by imWillX** [comment] 2018-03-07 00:33
@XXLuigiMario 

* ~~Missing messages~~
* ~~Missing effects~~
* ~~Keys 'preview.enabled' and 'preview.rows' are hierachically incorrect~~
* ~~**Section symbols are not converted back to ampersands**
I think this is fine as is, but if there is an issue that I don't know about, please let me know.~~
* ~~**Items with no name are incorrectly assigned the name of the Material type**
Not sure about this. `ItemMeta.hasDisplayName` is returning true, and `ItemMeta#getDisplayName` returns the type name.~~
* ~~Reward lines end with with an extra comma and space~~
* **'glow:true' is converted to 'arrow_infinite:10' and 'hide:true'**
Intended behavior.

**Comment by puigru** [comment] 2018-03-07 20:09
* **Section symbols are not converted back to ampersands**
I think this could confuse users using the plugin, nothing that I cannot change myself.
(I'd be as easy as replacing ChatColor.COLOR_CHAR)
* **Items with no name are incorrectly assigned the name of the Material type**
That seems really off to me. I'll try it out myself later.
* **'glow:true' is converted to 'arrow_infinite:10' and 'hide:true'**
Doesn't seem to be then properly parsed by CrateReloaded.

> [22:48:11] [Server thread/INFO]: [CrateReloaded] Enabling CrateReloaded v2.0.0-alpha-05
[22:48:11] [Server thread/INFO]: [CrateReloaded] v1_12_R1
[22:48:11] [Server thread/INFO]: [CrateReloaded] Animation Listener registered.
[22:48:11] [Server thread/INFO]: [CrateReloaded] Unable to parse: arrow_infinite:10
[22:48:11] [Server thread/INFO]: [CrateReloaded] Unable to parse: arrow_infinite:10
[22:48:11] [Server thread/INFO]: [CrateReloaded] Crate Configurations: crate.yml

**Comment by imWillX** [comment] 2018-03-10 23:55
@XXLuigiMario 

Do you have an example of the effect which is hierarchically incorrect?
 
10/10
~~Display name section symbols not converted back to ampersands~~

**Comment by puigru** [comment] 2018-03-11 00:15
@imWillX Well, instead of assigning each a number, it just puts them under the 'effect' key. You can see a screenshot in issue https://github.com/Hazebyte/CrateReloadedAPI/issues/24

**Comment by imWillX** [comment] 2018-03-11 07:07
Gotcha!

**Comment by imWillX** [comment] 2018-03-13 00:53
Fixed in latest build. Please reopen if there are any issues.

**Closed as completed** 2018-03-13 01:00 UTC
Labels: bug
